# general configuration
url: ''
baseurl: ''

compass:
  logo: "/images/historias.png"
  author: "Historias"
  tagline: "Una comunidad que es dedicada a transformar Guatemala."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
